# Generated by Django 5.0.6 on 2024-08-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_weightlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightlog',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
